---
title: "Exercises"
subtitle: "Task 4"
author: "Javier Fong - 100437994"
date: "11/5/2021"
output: 
  html_document:
    code_folding: show
    toc: true
    toc_float: true
    toc_depth: 4
    theme: flatly
---

# Exercise I 

```{r}
a = c(10:38)
print(a)

b = c(30:1)
print(b)

c = c(c(1:4),c(3:1))
print(c)

d = seq(2, 20, by = 2)
print(d)

e = c() 
for (i in 1:10) {e = c(e,c(1,2,3))}
print(e)

f = head(e,-2)
print(f)

g = paste("label", 1:30)
print(g)

h = paste("label", 1:30, sep="-")
print(h)

i = seq(0.1, 1, by = 0.1)
i = (i^2)*exp(i)
print(i)
```

# Exercise 2 

Implement: 

$$ r_1 = \sum_{x = 5}^{23} x^2 + 3 + \sqrt x $$

$$ r_2 = \sum_{x = 1}^{18} \frac{1.3^x}{x}$$

$$ r_3 = \sum_{x=1}^{10} \sum_{y=1}^{6} \frac{x^4}{3+y}$$

## With Loops
```{r}
r1 = 0
for (j in 5:23) { 
  r1 = r1 + (j^2 + 3 * j^0.5)
}
print(r1)

r2 = 0 
for (i in 1:18) {
  r2 = r2 + (1.3^i)/i
}
print(r2)

r3=0 
for (i in 1:10) {
  for (j in 1:6) { 
    r3 = r3 + (i^4)/(3+j)
  }
}
print(r3)
```

## Without Loops 
```{r}
x = 5:23
r1 = outer(x,1, function(x,y){return((x^2)+(3*(x^0.5)))})
print(sum(r1))

x = 1:18 
r2 = outer(x,1,function(x,y){return((1.3^x)/x)})
print(sum(r2))

x = 1:10
y = 1:6
r3 = outer(x,y,function(x,y){return((x^4)/(3+y))})
print(sum(r3))
```

# Exercise 3 

Create a matrix of 6x10 (rows x columns) of random numbers between 1 and 10. 
```{r}
set.seed(75)
M = matrix(
  sample(
    1:10
    , size=60
    , replace=TRUE
  ) 
  , nrow=6
  , ncol=10
)
print(M)
```

Count the number of values greater than 4 in each row.
```{r}
rowSums(M > 4)
```

Add the values of the second column to the third one. 
```{r}
M[,3] = M[,3] + M[,2]
print(M)
```

# Exercise 4

Create a matrix of 3x3 of random numbers between 1 and 10. 
```{r}
M2 = matrix(
  sample(
    1:10
    , size=9
    , replace=TRUE
  )
  , nrow=3
  , ncol=3)
print(M2)
```

Multiply by 2 the odd numbers in the matrix.

```{r}
M2 * ((M2 %% 2 == 1)+1)
```

